name: Doomsday
version: 1.0.0
main: gg.doomsday.core.DoomsdayCore
api-version: 1.20

commands:
  rocket:
    description: Launch missiles and manage rocket systems (Staff Only)
    usage: /rocket <missile_type> | /rocket reload | /rocket options | /rocket powder [amount] | /rocket helmet [amount] | /rocket items
    permission: rocket.use
  antiair:
    description: Manage anti-aircraft defense systems (Staff Only)
    usage: /antiair status | /antiair list | /antiair online <name> | /antiair offline <name> | /antiair reload
    permission: rocket.antiair
    aliases: [aa]
  nations:
    description: Comprehensive nations system with GUI (Players)
    usage: /nations | /nations leave | /nations info [nation] | /nations teleport [nation] | /nations missiles [nation] | /nations disasters [nation] | /nations items
    permission: rocket.use
    aliases: [nation, n]
  seasons:
    description: Manage game seasons (Staff Only)
    usage: /seasons current | /seasons create <id> | /seasons activate | /seasons archive
    permission: season.admin
    aliases: [season, s]
  disaster:
    description: Manage natural disasters (Staff Only)
    usage: /disaster trigger <nation> <disaster_type> | /disaster stop <nation> <disaster_type> | /disaster status [nation] | /disaster list | /disaster auto <enable|disable|status> | /disaster reload
    permission: rocket.disaster
  cc:
    description: Send colored chat messages using & color codes
    usage: /cc <message>
    permission: colorchat.use
  rr:
    description: Quick server reload command
    usage: /rr
    permission: rocket.reload
  r:
    description: Legacy command - redirects to new command structure
    usage: Use /rocket, /antiair, or /nations instead
    permission: rocket.use

permissions:
  rocket.use:
    description: Allows using /rocket
    default: true
  rocket.reload:
    description: Allows reloading rocket config
    default: op
  rocket.powder:
    description: Allows getting reinforcement powder
    default: op
  rocket.antiair:
    description: Allows managing anti-air defense systems
    default: op
  colorchat.use:
    description: Allows using /cc for colored chat
    default: true
  season.admin:
    description: Allows managing seasons (create, activate, archive)
    default: op
  rocket.disaster:
    description: Allows managing natural disasters (trigger, stop, reload)
    default: op
